### PR TITLE
Fixed the typo in Writing

### PR DESCRIPTION
**Pull request by hb2708**
This will solve the issue of linking Writing section

### CODE REVIEW

**Comment by hb2708** [comment]
Hey @EmaSuriano,

Please take a look at this small change.
The CI Failed coz the contentful accessToken is missing.

**Comment by hb2708** [comment]
@EmaSuriano how can i pass the token in the ci pipeline, can you take a look?

**Comment by hb2708** [comment]
[CI: Restart build]

**Comment by hb2708** [comment]
@EmaSuriano 
Found this from the failing log.

Encrypted environment variables have been removed for security reasons.
214See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by EmaSuriano** [comment]
Hey, @hb2708 thanks for the contribution :) Yeah, there is nothing I can do because they are disabling the env variables for external prs ... Nevertheless, your change won't break anything so I'm merging it right away 👍

**Comment by hb2708** [comment]
@EmaSuriano thanks again

**Pull request merged**
