### PR TITLE
Feat/youtube section

### PR DESCRIPTION
**Pull request by EmaSuriano**
# Youtube Section 🔥
## What is this pr about? 👀
Adding a new section of Youtube, the original idea was from @seanjun21

## Changes 🎁
- [x] Add plugin to fetch data
- [x] Modify Content model and Content
- [x] Add YOUTUBE_API to the `.env` file
- [x] Create Youtube section and re-use `CardSection` component
- [ ] Write README explaining:
  - How to show the Section inside the portfolio, obtaining the `channelD`
  - How to create a youtube API
  - How to configure the plugin with both values
- [ ] Upload test videos to mate account to preview this section in the default page.

## Screenshots 🖼 
image

### CODE REVIEW

**Comment by seanjun21** [comment]
@EmaSuriano Thanks for the mention. Glad you took the idea to implement this section.

https://github.com/seanjun21/seanjun-portfolio/commit/c44a0d5447ef37ec7009c4ca4278b2077d2c5bc6

This is the PR I made for my own branch. Perhaps, it could help you.
One thing I noticed, I haven't tested this starter without YouTube integration.
I know I have the channel up and going, but that's not everyone's case.
I made the fail-safe check just like you wrote inside the Medium section.
In case, the user does not enter YouTube id, the entire YouTube section should hide.

By the way, would it be okay if I present this starter on my channel with your name mentioned?
Not any time soon, since I just rebranded and have basically no subs.
Once I pick it up again, I think it would be nice to showcase your work and introduce GatsbyJS.

Thanks for all your work. Really looking forward to this PR.

**Comment by EmaSuriano** [comment]
Hello @seanjun21 sorry for the delayed answer, I've been traveling quite a lot and I didn't have time to take a look to this. I would love to close this pr but I'm having a lot of complexities to make this feature optional because I don't want to force everybody out there to render the YouTube section (the same thing I'm doing with the Writing section). Let me give you some context of what is happening:

In order to make the Writing section optional I'm providing a fake user, in this case `@medium` and then inside the component asking if the user has defined a `mediumUser` inside Contentful. In case not, I just don't render the section and problem solved!

The difference with this Section is that the plugin needs two values, one is the `channelId` (similar to the Writing Section) and also an `apiKey` value which needs to be manually generated inside the Google Developer Console. The main problem here is that I can't fake the `apiKey` therefore I can add the plugin if the developer didn't set it up. As I am not adding the plugin then the `StaticQuery` failed when it loads because I'm trying to access the value of the schema that does not exist ...

I tried several solutions, any of them works:
0. Conditional in the query: Due to `graphql` restrictions it's not possible to add interpolation inside template string, the community is suggesting to use `Fragment` to add condition. But the problem is the `Fragment` is going to be evaluated in the same way as the `StaticQuery` ❌
0. Try to wrap the component in a HOC, so I don't render it. The StaticQuery is being analyzed independently if inside my `index.js` I have the following condition `false && <MySection />`. So another fail here ❌
0. Searched how to mock the plugin but couldn't find anything relevant, there are some solutions to provide testing environment but in this case, I can't apply them. ❌
0. The last try that I was quite close to fixing it was to use the [babel macros](https://github.com/kentcdodds/preval.macro), that allow computing some code before the server starts. Therefore my idea was to generate the proper query for the Section, but sadly I wasn't able to accomplish it due to some weird error when trying to run `preval` inside the `Section`. ❌

It's sad to say but I can't find a solution to fix this problem, and I don't want to impact all the other users with this feature (which I would love to use for me too!). If by chance do you know a way to provide a condition inside the `StaticQuery` so I can change the data I fetched inside the Section it would really cool to know. Btw, in case we manage to solve this issue this is an incredible idea to share this with the community because I wasn't able to find any solution out there.

Thanks in advance!

**Comment by seanjun21** [comment]
@EmaSuriano wow, you really did your research there. Yes, I too was afraid we'd run into issues like that. I just didn't know Medium behaves differently compared to YouTube. So, I'm guessing it's close to impossible to create a starter with YouTube integration unless otherwise done manually (like how I added environment variables manually).

I understand that you do not want to impact other users. So, we can put a halt there. I will continue to use this version (YouTube version that I have on my own repository -- cloned version of yours). I know it's an awesome integration, but I haven't seen that many people programming and YouTubing at the same time. Unless there's a huge demand from everyone, I think it's good to close here and revisit when there's a better solution.

Thanks for listening and doing all the hard work. I'd love to present your work on my channel. I think this is the best Gatsby starter for tech bloggers.

**Comment by EmaSuriano** [comment]
Hi @seanjun21! Yeah it's a pity because I really wanted to merge this feature, but for the moment it's so hard to have something that will satisfy everyone.
I would love to check when you present this project in your channel, so let's keep in touch!

**Pull request closed without merging**
